export const appRoutes = {
  home: () => "/",
  login: () => "/login",
  register: () => "/register",
  forgotPassword: () => "/forgot-password",
  dashboard: () => "/dashboard",
  dashboardRequestAccess: () => "/dashboard/request-access",
  dashboardGroup: (groupId: string) => `/dashboard/${groupId}`,
  dashboardMembers: (groupId: string) => `/dashboard/${groupId}/members`,
  dashboardPolls: (groupId: string) => `/dashboard/${groupId}/polls`,
  dashboardPoll: (groupId: string, pollId: string) => `/dashboard/${groupId}/polls/${pollId}`,
  dashboardFundraising: (groupId: string) => `/dashboard/${groupId}/fundraising`,
  dashboardCampaign: (groupId: string, campaignId: string) =>
    `/dashboard/${groupId}/fundraising/${campaignId}`,
  dashboardCampaignContribute: (groupId: string, campaignId: string) =>
    `/dashboard/${groupId}/fundraising/${campaignId}/contribute`,
  dashboardEvents: (groupId: string) => `/dashboard/${groupId}/events`,
  dashboardEvent: (groupId: string, eventId: string) => `/dashboard/${groupId}/events/${eventId}`,
  dashboardPosts: (groupId: string) => `/dashboard/${groupId}/posts`,
  dashboardPost: (groupId: string, postId: string) => `/dashboard/${groupId}/posts/${postId}`,
  profile: () => "/profile",
  admin: () => "/admin",
  adminNeighborhood: (neighborhoodId: string) => `/admin/${neighborhoodId}`,
  adminGroups: (neighborhoodId: string) => `/admin/${neighborhoodId}/groups`,
  adminGroup: (neighborhoodId: string, groupId: string) =>
    `/admin/${neighborhoodId}/groups/${groupId}`,
  adminPolls: (neighborhoodId: string) => `/admin/${neighborhoodId}/polls`,
  adminPoll: (neighborhoodId: string, pollId: string) =>
    `/admin/${neighborhoodId}/polls/${pollId}`,
  adminFundraising: (neighborhoodId: string) => `/admin/${neighborhoodId}/fundraising`,
  adminCampaign: (neighborhoodId: string, campaignId: string) =>
    `/admin/${neighborhoodId}/fundraising/${campaignId}`,
  adminEvents: (neighborhoodId: string) => `/admin/${neighborhoodId}/events`,
  adminEvent: (neighborhoodId: string, eventId: string) =>
    `/admin/${neighborhoodId}/events/${eventId}`,
  adminPosts: (neighborhoodId: string) => `/admin/${neighborhoodId}/posts`,
  adminPost: (neighborhoodId: string, postId: string) => `/admin/${neighborhoodId}/posts/${postId}`,
  adminUsers: (neighborhoodId: string) => `/admin/${neighborhoodId}/users`,
  adminUser: (neighborhoodId: string, userId: string) => `/admin/${neighborhoodId}/users/${userId}`,
  adminMembers: (neighborhoodId: string) => `/admin/${neighborhoodId}/members`,
  platform: () => "/platform",
  platformNeighborhood: (neighborhoodId: string) => `/platform/${neighborhoodId}`,
  platformUsers: () => "/platform/users",
  platformUser: (userId: string) => `/platform/users/${userId}`,
  platformUserEdit: (userId: string) => `/platform/users/${userId}/edit`,
  legalHub: (lang = "en") => `/${lang}`,
  terms: (lang = "en") => `/${lang}/terms-of-service`,
  privacy: (lang = "en") => `/${lang}/privacy-policy`,
  dataDeletion: (lang = "en") => `/${lang}/data-deletion`,
};
